const disposableDomains = new Set([
  'tempmail.com',
  'throwaway.email',
  'guerrillamail.com',
  'mailinator.com',
  'yopmail.com',
  'sharklasers.com',
  'guerrillamailblock.com',
  'grr.la',
  'dispostable.com',
  'trashmail.com',
  'fakeinbox.com',
  'tempail.com',
  'temp-mail.org',
  'minutemail.com',
  'maildrop.cc',
  'harakirimail.com',
  'getairmail.com',
  'meltmail.com',
  'brefmail.com',
  'discard.email',
  'discardmail.com',
  'mailnesia.com',
  'tempr.email',
  'spamgourmet.com',
  'mytemp.email',
  'mohmal.com',
  'burnermail.io',
  'getnada.com',
  'emailondeck.com',
  'tempinbox.com',
  'throwawaymail.com',
  '10minutemail.com',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamail.de',
  'mailcatch.com',
  'trash-mail.com',
  'bugmenot.com',
  'mailexpire.com',
  'jetable.org',
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase();
  if (!domain) return false;
  return disposableDomains.has(domain);
}
